service: daniel-testing

frameworkVersion: '2 || 3'
	
useDotenv: true
plugins:
  - serverless-dotenv-plugin
provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

functions:
  getAllSpells:
    handler: handler.getAllSpells
    events:
    - http:
        path: spells/getAll
        method: POST
        cors: true
  addSpells:
    handler: handler.addSpell
    events:
    - http:
        path: spells/add
        method: POST
        cors: true
        addSpells:
  deleteSpell:
    handler: handler.deleteSpell
    events:
    - http:
        path: spells/delete
        method: POST
        cors: true
  getSpell:
    handler: handler.getSpell
    events:
    - http:
        path: spells/getSpell
        method: POST
        cors: true
  getDesc:
    handler: handler.getDesc
    events:
    - http:
        path: spells/getDesc
        method: POST
        cors: true

  getAllMeetups:
    handler: handler.getAllMeetups
    events:
    - http:
        path: meetups/getAll
        method: POST
        cors: true
  AddMeetups:
    handler: handler.addMeetups
    events:
    - http:
        path: meetups/addMeetups
        method: POST
        cors: true

  getAllTask:
    handler: handler.getAllTask
    events:
    - http:
        path: task/getAll
        method: POST
        cors: true
  addTask:
    handler: handler.addTask
    events:
    - http:
        path: task/add
        method: POST
        cors: true
  testMe:
    handler: handler.testMe
    events:
    - http:
        path: /test
        method: POST
        cors: true
  testMe2:
      handler: handler.testMe2
      events:
      - http:
          path: /test2
          method: POST
          cors: true
  getAllTaskList:
    handler: handler.getAllTaskList
    events:
      - http:
          path: /task/list
          method: POST
          cors: true
  getAllTaskListAgr:
    handler: handler.getAllTaskListAgr
    events:
      - http:
          path: /task/list/agr
          method: POST
          cors: true
        



